### ISSUE TITLE
making it better

### ISSUE THREAD

**Issue by uinstinct** [ak6306/kiitask#1]
## Problems
- The **logo** in [footer.ejs](https://github.com/ak6306/kiitask/blob/master/views/partials/footer.ejs) in **not visible**

![image](https://user-images.githubusercontent.com/61635505/82114245-3852aa00-9779-11ea-893a-8e53f3b3db6e.png)

- **load time** is close to 5s. It should be 3s at max.

## Suggestions
- adding too many _script sources_ slows down the page (**try to cache them on client side storage or combine them to a single js file** - it decreases page load)

**Comment by ak6306** [comment]
Okay looking into it right now. Actually, I am not using the logo. I will try and simplify the footer.
Thank You.

**Comment by uinstinct** [comment]
Okay, I have also made a pull request which make your site better.

*Just don't forget to add me in the contributor's list*
